# Group Assignment

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as sm
import scipy
#from scipy import stats
from statsmodels.graphics.regressionplots import plot_regress_exog, plot_fit, plot_leverage_resid2, influence_plot

In [2]:
df = pd.read_csv('36100232.csv')

In [6]:
df.tail(15)

,REF_DATE,GEO,DGUID,Seasonal adjustment,Activities,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
4045,2022-04,Canada,2016A000011124,Unadjusted,Other tourism activities,Jobs,190,thousands,3,v81684,1.1.12,100.6,NaN,NaN,NaN,1
4046,2022-04,Canada,2016A000011124,Unadjusted,Recreation and entertainment,Jobs,190,thousands,3,v81685,1.1.13,70.0,NaN,NaN,NaN,1
4047,2022-04,Canada,2016A000011124,Unadjusted,Travel agencies,Jobs,190,thousands,3,v81686,1.1.14,30.6,NaN,NaN,NaN,1
4048,2022-04,Canada,2016A000011124,Unadjusted,Other industries,Jobs,190,thousands,3,v81687,1.1.15,121.8,NaN,NaN,NaN,1
4049,2022-04,Canada,2016A000011124,Seasonally adjusted,Tourism activities,Jobs,190,thousands,3,v81658,1.2.1,621.5,NaN,NaN,NaN,1
4050,2022-04,Canada,2016A000011124,Seasonally adjusted,Total tourism industries,Jobs,190,thousands,3,v81659,1.2.2,500.5,NaN,NaN,NaN,1
4051,2022-04,Canada,2016A000011124,Seasonally adjusted,Transportation,Jobs,190,thousands,3,v81660,1.2.3,65.0,NaN,NaN,NaN,1
4052,2022-04,Canada,2016A000011124,Seasonally adjusted,Air transportation,Jobs,190,thousands,3,v81661,1.2.4,42.6,NaN,NaN,NaN,1
4053,2022-04,Canada,2016A000011124,Seasonally adjusted,Other transportation,Jobs,190,thousands,3,v64605557,1.2.17,22.4,NaN,NaN,NaN,1
4054,2022-04,Canada,2016A000011124,Seasonally adjusted,Accommodation,Jobs,190,thousands,3,v81667,1.2.10,120.6,NaN,NaN,NaN,1
4055,2022-04,Canada,2016A000011124,Seasonally adjusted,Food and beverage services,Jobs,190,thousands,3,v81668,1.2.11,216.5,NaN,NaN,NaN,1
4056,2022-04,Canada,2016A000011124,Seasonally adjusted,Other tourism activities,Jobs,190,thousands,3,v81669,1.2.12,98.4,NaN,NaN,NaN,1
4057,2022-04,Canada,2016A000011124,Seasonally adjusted,Recreation and entertainment,Jobs,190,thousands,3,v81670,1.2.13,67.8,NaN,NaN,NaN,1
4058,2022-04,Canada,2016A000011124,Seasonally adjusted,Travel agencies,Jobs,190,thousands,3,v81671,1.2.14,30.6,NaN,NaN,NaN,1
4059,2022-04,Canada,2016A000011124,Seasonally adjusted,Other industries,Jobs,190,thousands,3,v81672,1.2.15,121.0,NaN,NaN,NaN,1